### ISSUE TITLE
Fix #94 and #600 .

### ISSUE THREAD

**Issue by Dahershiser** [Dahershiser/hello-world#5]
Fix #94 and #600 .

## Tasks

- [x] Create new component `incoming-transactions-graph`;
- [x] Refactor component `mempool-graph`;
- [x] Refactor component `fee-distribution-graph`;
- [x] Add `incoming-transactions-graph` to `dashboard`;
- [x] Add `incoming-transactions-graph` to `statistics`;
- [x] Add `incoming-transactions-graph` to `television`;
- [x] Add `mempool-graph` to `dashboard`;
- [x] Add `mempool-graph` to `statistics`;
- [x] Add `mempool-graph` to `television`;
- [x] Remove `chartist.component`;

## TODO

- [ ] Inverted graph button;
- [ ] Write e2e testing;

## Preview
![preview-dashboard](https://user-images.githubusercontent.com/5798170/130310943-9da9b100-de22-4557-8555-ceb6ec3635b6.gif)
![preview-mempool-block](https://user-images.githubusercontent.com/5798170/130310942-653e0970-c517-4de4-ba59-52d7a04869cc.gif)
![preview-preload](https://user-images.githubusercontent.com/5798170/130310941-8807f467-f98e-444c-add6-624084a9af10.gif)
![preview-responsive](https://user-images.githubusercontent.com/5798170/130310939-4b6d8985-ee1f-4036-9389-1681eebd932f.gif)
![preview-responsive2](https://user-images.githubusercontent.com/5798170/130310937-8688efaf-6d70-4c3f-95ad-de00fb2b5578.gif)
![preview-graphs-page](https://user-images.githubusercontent.com/5798170/130310936-2d59119a-1e8a-44a6-859a-3513c73b8598.gif)
![preview-responsive3](https://user-images.githubusercontent.com/5798170/130310934-e8b6db94-4bf2-40c6-a630-b1fa5bf784f1.gif)
![preview-change-graph-page-timeinterval](https://user-images.githubusercontent.com/5798170/130310933-3cc49cd9-7f5b-4be1-80ae-c547e2e69cb9.gif)
![preview-responsive4](https://user-images.githubusercontent.com/5798170/130310930-e980a727-b5ae-43ae-ad8d-e3229829e63b.gif)

__Originally posted by @MiguelMedeiros in https://github.com/mempool/mempool/pull/738__
